import { create } from 'zustand';

export const useStore = create((set) => ({
  side: 'buy',
  selectedNetwork: null,
  selectedAsset: null,
  amount: 0,
  hash: '',
  transactionHash: '',
  clientDepositAddress: null,
  bankName: '',
  accountNumber: '',
  routingNumber: '',
  beneficiaryName: '',
  country: '',
  state: '',
  city: '',
  streetAddress: '',
  zipCode: '',
  setSide: (side) => set({ side }),
  setNetwork: (selectedNetwork) => set({ selectedNetwork }),
  setAsset: (selectedAsset) => set({ selectedAsset }),
  setAmount: (amount) => set({ amount }),
  setHash: (hash) => set({ hash }),
  setClientDepositAddress: (clientDepositAddress) =>
    set({ clientDepositAddress }),
  setBankName: (bankName) => set({ bankName }),
  setAccountNumber: (accountNumber) => set({ accountNumber }),
  setRoutingNumber: (routingNumber) => set({ routingNumber }),
  setBeneficiaryName: (beneficiaryName) => set({ beneficiaryName }),
  setCountry: (country) => set({ country }),
  setState: (state) => set({ state }),
  setCity: (city) => set({ city }),
  setStreetAddress: (streetAddress) => set({ streetAddress }),
  setZipCode: (zipCode) => set({ zipCode }),
}));
